### ISSUE TITLE
[Bug]: Server crashes upon starting

### ISSUE THREAD

**Issue by BookerCatch** [Mrbysco/Lunar#1]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 43.2.21

### Minecraft version

1.19.2

### Mod version

0.1.0

### Java version

Temurin JRE 17.0.8+7 

### Issue Description

Server crashes upon starting. Please see attached logs

### Additional Information

[Latest Log](https://pastebin.com/hnNBiFBV)
[Crash Log](https://pastebin.com/TYKp4MHM)

**Comment by Mrbysco** [comment]
A fix will be available soon (as soon as Curse approves the new upload)
