### ISSUE TITLE
[Bug]: Chat Spam

### ISSUE THREAD

**Issue by Ashuntoi** [Mrbysco/Lunar#11]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 43.2.21

### Minecraft version

1.19.2

### Mod version

Lunar-forge-1.19.2-0.1.7

### Java version

jdk-17.0.5.8-hotspot

### Issue Description

Hello,

When it's rain and a event moon append the mod spam this text in the chat : Due to bad weather the effects of Moon have been cleansed!

**Comment by Mrbysco** [comment]
A new version has already been uploaded. it's just been stuck in review so it'll most likely get approved tomorrow
