### ISSUE TITLE
[Suggestion]: Option to disable cancelling moons due to bad weather.

### ISSUE THREAD

**Issue by NekoLeila** [Mrbysco/Lunar#12]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Not sure why this is a thing? but I'd really love the option to disable it.

**Comment by Mrbysco** [comment]
The reason it's a thing is because the method I call to check if it's night also triggers if it's storming which would mean it'll start a moon when it rains

**Comment by NekoLeila** [comment]
Ok, that makes sense. I still think it'd be nice to have the option to turn it off. Seems like 90% of my lunar events get canceled cuz of weather.
