### ISSUE TITLE
[Bug]: 1.19.2 Fabric startup crash, crash logs complain about Pehkui and the scaling of the moon.

### ISSUE THREAD

**Issue by nickdehkordi** [Mrbysco/Lunar#13]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.15.3

### Minecraft version

1.19.2

### Mod version

0.1.10

### Java version

Unsure how to check

### Issue Description

When Lunar is disabled, the modpack works fine. With Lunar enabled, the modpack crashes before Minecraft even opens.

### Additional Information

https://pastebin.com/6h4j4qBU

**Comment by Mrbysco** [comment]
I have no clue, there's probably a mod mixin into the same stuff but in a way that's incompatible with Lunar

**Comment by Mrbysco** [comment]
From the crashlog I can't really tell what mod as it's not really an informative crash

**Comment by Mrbysco** [comment]
Do you have a log? (with any sensitive data (computer name etc) removed)

**Comment by Sunconure11** [comment]
Do you have Enhanced Celestials, Botania, or Spyglass Astronomy?

**Comment by nickdehkordi** [comment]
> Do you have Enhanced Celestials, Botania, or Spyglass Astronomy?

Yes, enhanced celestials. I will try removing that.

**Comment by nickdehkordi** [comment]
This worked. Thank you to all.
