### ISSUE TITLE
[Bug]: Crash when Bloodmoon has been started.

### ISSUE THREAD

**Issue by LordRomzessV** [Mrbysco/Lunar#3]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

47.1.44

### Minecraft version

1.20.1

### Mod version

0.1.2

### Java version

java-runntime-gamma (17.0.3)

### Issue Description

A bug happened! When i saw a message about starting of bloodmoon my game has instantly crashed, And it has crash again if i try to reload current world.

[crash-2023-08-22_19.26.25-server.txt](https://github.com/Mrbysco/Lunar/files/12410797/crash-2023-08-22_19.26.25-server.txt) - first crash
[crash-2023-08-22_19.30.42-server.txt](https://github.com/Mrbysco/Lunar/files/12410794/crash-2023-08-22_19.30.42-server.txt) 
[crash-2023-08-22_19.32.08-server.txt](https://github.com/Mrbysco/Lunar/files/12410796/crash-2023-08-22_19.32.08-server.txt)
[crash-2023-08-22_19.38.14-server.txt](https://github.com/Mrbysco/Lunar/files/12410798/crash-2023-08-22_19.38.14-server.txt) - crash after update from 0.1.1 to 0.1.2

**Comment by Mrbysco** [comment]
A fix is being uploaded (0.1.3)
