### ISSUE TITLE
[Bug]: Startup crash Fabric 1.20.1

### ISSUE THREAD

**Issue by pewblaze** [Mrbysco/Lunar#4]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

0.14.22

### Minecraft version

1.20.1

### Mod version

Lunar-fabric-1.20.1-0.1.2

### Java version

Java 8 Update 341

### Issue Description

I cant start the game - it crashes :( 

### Additional Information

https://pastebin.com/ubdrWBB9

**Comment by Mrbysco** [comment]
Fixed in 0.1.4 which will be up shortly
I forgot to add compatibility for Architectury mods
