### ISSUE TITLE
[Bug]: Cant start the game (Fabric 1.20.1)

### ISSUE THREAD

**Issue by pewblaze** [Mrbysco/Lunar#6]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.14.22

### Minecraft version

1.20.1

### Mod version

Lunar-fabric-1.20.1-0.1.4

### Java version

Java 8 Update 341

### Issue Description

Cant start the game again ^^"

### Additional Information

https://pastebin.com/tKnqEWm3

**Comment by Mrbysco** [comment]
Are you sure it's Lunar? As I don't see anything pointing to Lunar

**Comment by pewblaze** [comment]
It works without Lunar, thats why im suspecting it. But it could be some other mod comp. - not sure about that ^^"

**Comment by Mrbysco** [comment]
I have a test version for you to try to see if it fixes it, if it does I'll have it published (I have to upload it as a zip as Github won't allow me to upload .jar files)
So please unzip it first as the jar is inside of the zip.
[0.1.5.zip](https://github.com/Mrbysco/Lunar/files/12433687/0.1.5.zip)

**Comment by pewblaze** [comment]
Unfortunately it didnt work :(
Heres the new log:
https://pastebin.com/47AwhDyL

It says the exact same thing. I tried to disable the mods mentioned like addittionalattributes, animatica, etc. -> but it always comes another mod after another new mod that couldnt start due to prelaunch ^^"

**Comment by Mrbysco** [comment]
Yeah I have no clue, I tried to see if Lunar is somehow incompatible with Animatica but I was even able to load with that mod

**Comment by pewblaze** [comment]
Ill try to disable some mods if ive got time, maybe ill find the cause :)

**Comment by SickElmo-GH** [comment]
![image](https://github.com/Mrbysco/Lunar/assets/7932564/3e711119-d491-464e-a190-2ada1d31850c)

I got this problem if I try to enter a brand new world. It works fine if I don't have lunar installed.
These all the mods I've loaded:

- Lunar-fabric-1.20.1-0.1.4
- cloth-config-11.1.106-fabric
- fabric-api-0.87.0+1.20.1

**Comment by Mrbysco** [comment]
@Sickelmo83 Please in the future create a separate issue, your issue is unrelated to this issue (I did fix it though and a new build is being uploaded)

**Comment by Linguardium** [comment]
MixinTargetAlreadyLoadedException.

You load the Constants class in your mixin plugin onLoad event, which loads the Identity/ResourceLocation class among others, which causes those classes to load whatever they reference creating a chain of events leading to Mixin trying to modify classes you have force-loaded WAY too early.

**Comment by Mrbysco** [comment]
> Ill try to disable some mods if ive got time, maybe ill find the cause :)

Could you test [Lunar-fabric-1.20.1-0.1.5.1.zip](https://github.com/Mrbysco/Lunar/files/12480623/Lunar-fabric-1.20.1-0.1.5.1.zip)? I've changed the reference to Constants to a simple System.out.println as to not load the Constants class too early.

**Comment by pewblaze** [comment]
Sure I will try it this evening :)

**Comment by pewblaze** [comment]
The game/server starts now!
But it crashes after the world is created, heres the crash log and latest.log
https://gist.github.com/pewblaze/0536d64daa2ff26259d088c71d35601e

**Comment by Mrbysco** [comment]
Ah but that's an easy fix 😮 Will publish a new build that should once and for all fix this issue :)

**Comment by Linguardium** [comment]
you may want to look into abstracting SyncEventMessage so that the logic is all common, then extend/implement from the platforms for platform specific actions. That way you arent chasing the same bug on both sides with copied logic. Fabric side offers FabricPacket with a "write" method that could directly call the super encode to write the buffer instead of having the packet writing in 2 places, and the packet type creation would utilize the existing decode function through a similar super call
