### ISSUE TITLE
[Bug]: Possible incompat with Porting Lib

### ISSUE THREAD

**Issue by Sunconure11** [Mrbysco/Lunar#9]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Quilt 0.20.2

### Minecraft version

1.19.2

### Mod version

0.1.6

### Java version

Java 18

### Issue Description

This mod appears to be incompatible with Porting Lib, a dependency used by Fabric Create

### Additional Information

https://pastebin.com/sySD7QsA

**Comment by Sunconure11** [comment]
Okay, so the error didn't happen a second time, but it is similar to another error in another mod, Enhanced Celestials.

**Comment by Sunconure11** [comment]
https://github.com/CorgiTaco/Enhanced-Celestials/issues/175

**Comment by Mrbysco** [comment]
I don't develop for quilt, can you reproduce it with fabric?

**Comment by Sunconure11** [comment]
It happened only once. If it happens again I’ll let you know.

**Comment by Mrbysco** [comment]
If it happens again please reply to this issue
